version: '3.8'

services:

  mysql-service:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=demo_db
    ports:
      - "3307:3306"
    restart: always

  springboot-service:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - mysql-service
    restart: always
